
typedef enum USB_COMMANDS
{
	COMMAND_NONE = 0,
	COMMAND_BIG_DATA = 1,
	COMMAND_SET_FREQ = 2,
	COMMAND_START_SAMPLING = 3,
	COMMAND_SAMPLING_COMPLETE = 4,
	COMMAND_SAMPLING_BUFFER_SIZE = 5,
	COMMAND_GET_SAMPLES = 6,
} USB_COMMANDS;